export const DUMMY_EXPENSES = [
  {
    id: 'e1',
    description: 'Toilet Paper',
    price: 94.12,
    date: new Date(2020, 7, 14),
  },
  {
    id: 'e2',
    description: 'New TV',
    price: 799.49,
    date: new Date(2021, 2, 12),
  },
  {
    id: 'e3',
    description: 'Car Insurance',
    price: 294.67,
    date: new Date(2021, 2, 28),
  },
  {
    id: 'e4',
    description: 'New Desk (Wooden)',
    price: 450,
    date: new Date(2021, 5, 12),
  },
  {
    id: 'e5',
    description: 'Toilet Paper',
    price: 94.12,
    date: new Date(2020, 7, 14),
  },
  {
    id: 'e6',
    description: 'New TV',
    price: 799.49,
    date: new Date(2021, 2, 12),
  },
  {
    id: 'e7',
    description: 'Car Insurance',
    price: 294.67,
    date: new Date(2021, 2, 28),
  },
  {
    id: 'e8',
    description: 'New Desk (Wooden)',
    price: 450,
    date: new Date(2021, 5, 12),
  },
  {
    id: 'e9',
    description: 'Toilet Paper',
    price: 94.12,
    date: new Date(2020, 7, 14),
  },
  {
    id: 'e10',
    description: 'New TV',
    price: 799.49,
    date: new Date(2021, 2, 12),
  },
  {
    id: 'e11',
    description: 'Car Insurance',
    price: 294.67,
    date: new Date(2021, 2, 28),
  },
  {
    id: 'e12',
    description: 'New Desk (Wooden)',
    price: 450,
    date: new Date(2021, 5, 12),
  },
];

export const DUMMY_BARCODE_DATA = {
  products: [
    {
      barcode_number: '016571951603',
      barcode_formats: 'UPC-A 016571951603, EAN-13 0016571951603',
      mpn: '',
      model: '',
      asin: '',
      title: 'SparkIce Water Coconut',
      category: 'Food, Beverages & Tobacco',
      manufacturer: '',
      brand: 'Sparkling Ice',
      contributors: [],
      age_group: '',
      ingredients:
        'Carbonated Water, Natural Flavour, Malic Acid, Coconut Water Concentrate, Potassium Benzoate, Sucralose, Ester Gum, Calcium Disodium Edta, Colour',
      nutrition_facts: 'Salt 0.00497 g.',
      energy_efficiency_class: '',
      color: '',
      gender: '',
      material: '',
      pattern: '',
      format: '',
      multipack: '',
      size: '503 mL',
      length: '',
      width: '',
      height: '',
      weight: '',
      release_date: '',
      description: 'Sparkling Ice Sparkling Water Coconut Pineapple 503 ml (bottle).',
      features: [],
      images: [
        'https://images.barcodelookup.com/81544/815445777-1.jpg',
        'https://images.barcodelookup.com/81544/815445777-2.jpg',
        'https://images.barcodelookup.com/81544/815445777-3.jpg',
      ],
      last_update: '2023-12-22 10:02:06',
      stores: [
        {
          name: 'Voilà',
          country: 'CA',
          currency: 'CAD',
          currency_symbol: '$',
          price: '2.29',
          sale_price: '',
          tax: [],
          link: 'https://voila.ca/region-redirect/3809?target=%2Fproducts%2F632449EA%2Fdetails%3Flanguage%3Den-CA',
          item_group_id: '',
          availability: '',
          condition: '',
          shipping: [],
          last_update: '2023-12-22 10:02:06',
        },
      ],
      reviews: [],
    },
  ],
};
